[NetworkSetup] try to fix :
   File "/usr/lib/enigma2/python/Screens/NetworkSetup.py", line 907, in queryWirelessDevice
   File "/usr/lib/python3.10/site-packages/wifi/scan.py", line 72, in all
wifi.exceptions.InterfaceError: b"wlan0     Interface doesn't support scanning : Device or resource busy"