RecordTimer avoid BS for log entry. This does not solve the root cause of:
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/timer.py", line 218, in calcNextActivation
  File "/usr/lib/enigma2/python/timer.py", line 284, in processActivation
  File "/usr/lib/enigma2/python/RecordTimer.py", line 596, in doActivate
  File "/usr/lib/enigma2/python/RecordTimer.py", line 275, in activate
  File "/usr/lib/enigma2/python/RecordTimer.py", line 163, in log
AttributeError: 'dict' object has no attribute 'append'
(PyObject_CallObject(<bound method RecordTimer.calcNextActivation of <RecordTimer.RecordTimer instance at 0x1284828>>,()) failed)