[pmt] fix build error
error: suggest parentheses around '&&' within '||'
(cherry picked from commit 167575f1b45994984ba4125e826de81d11a07101)
(cherry picked from commit ccad9d04c52c45b1f307bcead3f05f6963dca7f6)