[PluginBrowser] * remove callbacks on close
Fix:
2023-05-15 16:31:57.0494   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 416, in opkgCallback
2023-05-15 16:31:57.0501 AttributeError: 'PluginDownloadManager' object has no attribute 'opkgObj'
2023-05-15 16:31:57.0502 [ePyObject] (PyObject_CallObject(<bound method OpkgComponent.cmdFinished of <Components.Opkg.OpkgComponent object at 0xafcf6150>>,(0,)) failed)

(cherry picked from commit 9028b01568a532ab8d629614849f48faa4decb73)