[Systemplugins/SoftwareManager/plugin.py] - Fix BS The call for language.delLanguage() no longer exists since https://github.com/openatv/enigma2/commit/c73bc0cdaa095768782b27223494b6aeab3b922c#diff-ff664b156965d84e90da6cb27836197173d8ceb5690c5330e4af5fac9e2c1571 TO-DO: Check if previously deleted languages get re-installed on updating enigma2 .
2021-08-23 13:59:50+0200 [-] Traceback (most recent call last):
2021-08-23 13:59:50+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
2021-08-23 13:59:50+0200 [-]     response = self.actions[action]()
2021-08-23 13:59:50+0200 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 1778, in exit
2021-08-23 13:59:50+0200 [-]     language.delLanguage()
2021-08-23 13:59:50+0200 [-] AttributeError: 'Language' object has no attribute 'delLanguage'