Really fix eConsoleAppContainer write
Clean up for commit 8800ca10e88061b317c256f3fa90ecf486551648
This should fix messages like:
TypeError: 1st arg must be a string, ...