FixedMenu: Fix GS when trying to access a invalid Tuple
Eg when using CutListEditor Plugin and it's menu selection to avoid:
IndexError: tuple index out of range
I did add the sanerty check in to avoid a possible other GSOD in case
this object is used elsewhere while selection could be still None