Hotkey: Small changes required for previous commit
To avoid an ImportError: cannot import name SimpleChannelSelection

Sorry I forgot to commit these changes in Hotkey.py with my previous
commit. Thanks IMS for reporting!