[Console] * fix crash :
08:49:26.1170   File "/usr/lib/enigma2/python/Screens/Console.py", line 92, in keyCancel
08:49:26.1174   File "/usr/lib/enigma2/python/Screens/Console.py", line 236, in stopTimer
08:49:26.1182 AttributeError: 'Console' object has no attribute 'baseTitle'. Did you mean: 'setTitle'?

Close #3383

(cherry picked from commit 0a3946178f1e5c90c83a7170be6866da878b94d4)