[Menu] add missing gotoStandby
fix crash:
`
19:42:39.5202   File "/usr/lib/enigma2/python/Screens/Menu.py", line 492, in execText
19:42:39.5204   File "<string>", line 6, in <module>
19:42:39.5207 AttributeError: 'Menu' object has no attribute 'gotoStandby'
`