NimManager: make sure that summary_stack has items before pop
IndexError: pop from empty list error can occur if we are trying
to pop from summary_stack without checking that has items.

Cherry picked but slightly changed from: https://github.com/athoik/enigma2/commit/e107c43d0aead3286f13abcdafac7eda0b40f304

Thanks Adhoik!!!!