[PluginComponent] add sanity check in remove plugin (#3714)
File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 316, in
requestClose
  File
"/usr/lib/enigma2/python/Components/PluginComponent.py", line 104, in
readPluginList
  File
"/usr/lib/enigma2/python/Components/PluginComponent.py", line 37, in
removePlugin
ValueError: list.remove(x): x not in list

(cherry picked from commit 15a422f5d6c66e3e27641d95049272e47fb884e1)