Revert "Do not use list as variable in ConfigList"
This reverts commit 705a7940265393ef60e31bfcc9b885ff7ac6ec1a.

now we have allways

   return self.__list
AttributeError: 'ConfigList' object has no attribute '_ConfigList__list'