[InfoBarGenerics.py] fix crash due to stupidness on last merge... Traceback (most recent call last):   File "/usr/lib/enigma2/python/mytest.py", line 41, in <module>     from Screens import InfoBar   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 23, in <module>     from Screens.InfoBarGenerics import InfoBarShowHide, \ ImportError: cannot import name 'InfoBarPiP' from 'Screens.InfoBarGenerics' (/usr/lib/enigma2/python/Screens/InfoBarGenerics.py)