fix -  dvb/demux.cpp:544:79: error: ‘r’ was not declared in this scope
 eWarning("[eDVBRecordFileThread] poll: aio_return returned failure: %d %m", r);

(cherry picked from commit 3828b34cc98f4839c3cdebf659003bc6ff803fa2)