[SatConfig] * fix crash for non unicable advanced details
21:43:54.5457   File "/usr/lib/enigma2/python/Screens/Satconfig.py", line 919, in __init__
21:43:54.5462   File "/usr/lib/enigma2/python/Screens/Satconfig.py", line 1078, in updateList
21:43:54.5468 AttributeError: 'ConfigNothing' object has no attribute 'lof'
(cherry picked from commit 577508b4a525d0e922fdda274743494c58429c21)