[PowerTimer] * add missing init of netbytes, netbytes_time
Fix crash:

2023-07-21 21:55:01.3308   File "/usr/lib/enigma2/python/timer.py", line 47, in calcNextActivation
2023-07-21 21:55:01.3754   File "/usr/lib/enigma2/python/timer.py", line 77, in processActivation
2023-07-21 21:55:01.3758   File "/usr/lib/enigma2/python/RecordTimer.py", line 291, in doActivate
2023-07-21 21:55:01.3762   File "/usr/lib/enigma2/python/RecordTimer.py", line 962, in activate
2023-07-21 21:55:01.3765   File "/usr/lib/enigma2/python/PowerTimer.py", line 392, in isAutoDeepstandbyEnabled
2023-07-21 21:55:01.3768   File "/usr/lib/enigma2/python/PowerTimer.py", line 1075, in getNetworkTraffic
2023-07-21 21:55:01.3774 AttributeError: 'PowerTimerEntry' object has no attribute 'netbytes'